coLearning_website/urls.py
from django.contrib import admin
from django.urls import path, include
from home_page.views import blog_post
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls')),
    path('profile_settings/',include('user_profile_page_settings.urls')), # profile_settings/<str:pk>/
    path('profile/', include('user_profile_page_main.urls')),
    path('social_space/', include('social_space.urls')),
    path('blog_post/',blog_post)
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home_page/urls.py
from django.urls import path
from home_page.views import home, post_question, post_video, post_blog, SignUp, LoginUser, blog_post, comment_display
from django.contrib.auth import views

app_name = 'home_page'

urlpatterns = [
    
    path('',home, name = 'home'),
    path('post/question/',post_question, name = "post_question"),
    path('post/video/',post_video, name = "post_video"),
    path('post/blog/',post_blog, name='post_blog'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('blog/<int:blog_id>',blog_post, name="blog_post"),
    path('comment/',comment_display, name="comment_display")

]
   

user_profile_page_main/urls.py
from django.urls import path
from user_profile_page_main.views import profile_page, post_like, post_dislike, post_reaction, user
from user_profile_page_main import views

app_name = 'user_profile_page_main'

urlpatterns = [
    
    path('',profile_page, name = 'profile_page'),
    path('post-reaction/', post_reaction, name="post_reaction"),
    path('postLike/',post_like, name="post_like"),
    path('postDislike/', post_dislike, name="post_dislike"),
    path('user/<int:user_id>/',user, name='user'),
    path("followToggle/<int:profileUserId>/", views.followToggle, name="followToggle")

]

user_profile_page_settings/urls.py
from django.urls import path
from user_profile_page_settings.views import account_dashboard, upload_photo

app_name = 'user_profile_page_settings'

urlpatterns = [
    
    path('',account_dashboard, name = 'settings'),
    path('image_upload/', upload_photo, name='upload_photo')


]

user_profile_page_settings/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    genderChoice = [ 
        ('Male',"Male"),
        ('Female',"Female")
    ]

    maritialStatusChoice = [ 
        ('Single','Single'),
        ('Married','Married'),
        ('Divorced','Divorced'),
        ('Seperated','Seperated'),
        ('Widowed','Widowed')
    ]

    states = [
        ("No_State","NA"),
        ("Alabama","AL"),
        ("Alaska","AK"),
        ("Arizona","AZ"),
        ("Arkansas","AR"),
        ("California","CA"),
        ("Colorado","CO"),
        ("Connecticut","CT"),
        ("Delaware","DE"),
        ("District of Columbia","DC"),
        ("Florida","FL"),
        ("Georgia","GA"),
        ("Hawaii","HI"),
        ("Idaho","ID"),
        ("Illinois","IL"),
        ("Indiana","IN"),
        ("Iowa","IA"),
        ("Kansas","KS"),
        ("Kentucky","KY"),
        ("Louisiana","LA"),
        ("Maine","ME"),
        ("Maryland","MD"),
        ("Massachusetts","MA"),
        ("Michigan","MI"),
        ("Minnesota","MN"),
        ("Mississippi","MS"),
        ("Missouri","MO"),
        ("Montana","MT"),
        ("Nebraska","NE"),
        ("Nevada","NV"),
        ("New Hampshire","NH"),
        ("New Jersey","NJ"),
        ("New Mexico","NM"),
        ("New York","NY"),
        ("North Carolina","NC"),
        ("North Dakota","ND"),
        ("Ohio","OH"),
        ("Oklahoma","OK"),
        ("Oregon","OR"),
        ("Pennsylvania","PA"),
        ("Rhode Island","RI"),
        ("South Carolina","SC"),
        ("South Dakota","SD"),
        ("Tennessee","TN"),
        ("Texas","TX"),
        ("Utah","UT"),
        ("Vermont","VT"),
        ("Virginia","VA"),
        ("Washington","WA"),
        ("West Virginia","WV"),
        ("Wisconsin","WI"),
        ("Wyoming","WY")
        
    ]
    following = models.ManyToManyField(
        "self", blank=True, related_name="followers", symmetrical=False
    )
    birthDate = models.DateField(null = True, blank=True)
    email = models.EmailField(max_length=254)
    website = models.URLField(max_length = 200, blank=True)
    phoneNumber = models.CharField(max_length=12, blank=True)
    country = models.CharField(max_length=50,blank=True)
    state = models.CharField(default="NA",max_length=20,choices=states)
    city = models.CharField(max_length=50,blank=True)
    description = models.TextField(blank=True)
    birthPlace = models.TextField(blank=True)
    gender = models.CharField(max_length=6, choices=genderChoice,default="Male")
    occupation = models.TextField(blank=True)
    maritialStatus = models.CharField(max_length=9, choices=maritialStatusChoice, default="Single")
    profileImage = models.ImageField(null = True,blank = True,upload_to='static/user_profile_page_settings/profileImages/', default='/static/default_images/bounlogo.png')
    backgroundImage = models.ImageField(null = True,blank = True,upload_to='static/user_profile_page_settings/profileImages/', default='/static/default_images/someImage.jpeg')
    facebookAccount = models.URLField(blank=True)

    def __str__(self) -> str:
        return str(self.id) + '_' + self.first_name + '_' + self.last_name

user_profile_page_settings/forms.py
from django import forms
from user_profile_page_settings.models import User

class ProfileInformationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'birthDate', 'website', 'phoneNumber', 'country', 'state', 'city', 'description', 'gender', 'birthPlace', 'occupation', 'maritialStatus']

class ProfileInformationForm_Image(forms.ModelForm):
    class Meta:
        model = User
        fields = ["profileImage","backgroundImage"]

user_profile_page_settings/views.py
from user_profile_page_main.views import profile_page
from django.shortcuts import render
from user_profile_page_settings.forms import ProfileInformationForm, ProfileInformationForm_Image
from user_profile_page_settings.models import User

# Create your views here.
def account_dashboard(request):

    user = User.objects.get(id=request.user.id)
    usStates = User.states
    genders = User.genderChoice
    maritialStatus = User.maritialStatusChoice 
    form = ProfileInformationForm(instance=user)


    if request.method == "POST":
        form = ProfileInformationForm(request.POST,request.FILES, instance=user)

        if form.is_valid():
            form.save(commit=True)
            print("Printing post: " , request.POST)
            return profile_page(request)
        else:
            print(form.errors)

    context = {'user':user,'states':usStates, 'genders':genders, 'maritialStatus':maritialStatus, 'form':form}

    return render(request,'user_profile_page_settings/account_profile_information.html',context)

def upload_photo(request):

    user = User.objects.get(id=request.user.id)
    form =  ProfileInformationForm_Image(request.POST,request.FILES, instance=user)

    if request.method == "POST":
        form = ProfileInformationForm_Image(request.POST,request.FILES, instance=user)

        if form.is_valid():
            form.save(commit=True)
            return profile_page(request)
        else:
            print(form.errors)

    context = {"form":form,'user':user}

    return render(request, 'user_profile_page_settings/image_uploader.html',context)

templates/user_profile_page_settings/account_profile_information.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>

	<title>Your Account - Personal Information</title>

	<!-- Required meta tags always come first -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="x-ua-compatible" content="ie=edge">


	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/Bootstrap/dist/css/bootstrap-reboot.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/Bootstrap/dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/Bootstrap/dist/css/bootstrap-grid.css' %}">

	<!-- Main Styles CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/css/main.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/css/fonts.min.css' %}">

	<!-- Main Font -->
	<script src="{%static 'user_profile_page_settings/js/webfontloader.min.js' %}"></script>
	<script>
		WebFont.load({
			google: {
				families: ['Roboto:300,400,500,700:latin']
			}
		});
	</script>


</head>
<body>
{%  include 'user_profile_page_settings/header.html' %}



{%  include 'user_profile_page_settings/navbar.html' %}





<!-- Your Account Personal Information -->

<div class="container">
	<div class="row">
		<div class="col col-xl-9 order-xl-2 col-lg-9 order-lg-2 col-md-12 order-md-1 col-sm-12 col-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<h6 class="title">Personal Information</h6>
				</div>
				<div class="ui-block-content">

					{%  include 'user_profile_page_settings/form.html' %}
					
				</div>
			</div>
		</div>

		
		{%  include 'user_profile_page_settings/sidebar.html' %}		

			
	</div>
</div>

<!-- ... end Your Account Personal Information -->






<a class="back-to-top" href="#">
	<img src="{% static 'user_profile_page_settings/svg-icons/back-to-top.svg' %}" alt="arrow" class="back-icon">
</a>



<!-- JS Scripts -->
<script src="{% static 'user_profile_page_settings/js/jquery-3.2.1.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.appear.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.mousewheel.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/perfect-scrollbar.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.matchHeight.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/svgxuse.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/imagesloaded.pkgd.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/Headroom.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/velocity.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/ScrollMagic.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.waypoints.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.countTo.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/popper.min.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/material.min.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/bootstrap-select.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/smooth-scroll.js' %}"></script>
<!-- <script src="{% static 'user_profile_page_settings/js/selectize.js' %}"></script> -->
<script src="{% static 'user_profile_page_settings/js/swiper.jquery.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/moment.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/daterangepicker.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/simplecalendar.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/fullcalendar.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/isotope.pkgd.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/ajax-pagination.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/Chart.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/chartjs-plugin-deferred.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/circle-progress.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/loader.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/run-chart.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.gifplayer.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/mediaelement-and-player.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/mediaelement-playlist-plugin.min.js' %}"></script>

<script src="{% static 'user_profile_page_settings/js/base-init.js' %}"></script>
<script defer src="{% static 'user_profile_page_settings/fonts/fontawesome-all.js' %}"></script>

<script src="{% static 'user_profile_page_settings/Bootstrap/dist/js/bootstrap.bundle.js' %}"></script>

</body>
</html>

templates/user_profile_page_settings/form.html
{%load static%}


<!-- Personal Information Form  -->
{% block content %}  
					
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">

        <div class="col col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group label-floating">
                <label class="control-label">First Name</label>
                    {{form.first_name }}
            </div>

            <div class="form-group label-floating">
                <label class="control-label">Your Email</label>
                <!-- <input name = 'email' class="form-control" placeholder="" type="email" value="{{user.email}}"> 	 -->
                    {{form.email}}
            </div>

            <div class="form-group date-time-picker label-floating">
                <label class="control-label">Your Birthday</label>
                <!-- <input name="datetimepicker" value="{{user.birthDate}}" /> -->
                {{form.birthDate}}
                <span class="input-group-addon">
                                        <svg class="olymp-month-calendar-icon icon"><use xlink:href="{% static 'user_profile_page_settings/svg-icons/sprites/icons.svg' %} #olymp-month-calendar-icon"></use></svg>
                                    </span>
            </div>
        </div>

        <div class="col col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group label-floating">
                <label class="control-label">Last Name</label>
                <!-- <input name = "last_name" class="form-control" placeholder="" type="text" value="{{user.last_name}}"> -->
                {{form.last_name}}

            </div>

            <div class="form-group label-floating">
                <label class="control-label">Your Website</label>
                <!-- <input name = "website" class="form-control" placeholder="" type="url" value="https://{{user.website}}"> -->
                {{form.website}}
            </div>


            <div class="form-group label-floating">
                <label class="control-label">Your Phone Number</label>
                <!-- <input name = "phoneNumber" class="form-control" placeholder="" type="text" value="{{user.phoneNumber}}"> -->
                {{form.phoneNumber}}
            </div>
        </div>

        <div class="col col-lg-4 col-md-4 col-sm-12 col-12">
            <div class="form-group label-floating is-select">
                <label class="control-label">Your Country</label>
                {{form.country}}
                <!-- <select class="selectpicker form-control">
                    <option value="US">United States</option>
                    <option value="AU">Australia</option>
                </select> -->
            </div>
        </div>
        <div class="col col-lg-4 col-md-4 col-sm-12 col-12">
            <div class="form-group label-floating is-select">
                <label class="control-label">Your State / Province</label>
                <!-- <select class="selectpicker form-control">
                    {% for state in form.state %}
                        
                        <option value="{{state}}">{{state}}</option>

                    {% endfor %}

                   
                    
                </select> -->
                {{form.state}}
            </div>
        </div>
        <div class="col col-lg-4 col-md-4 col-sm-12 col-12">
            <div class="form-group label-floating is-select">
                <label class="control-label">Your City</label>
                <!-- <select class="selectpicker form-control">
                    <option value="SF">San Francisco</option>
                    <option value="NY">New York</option>
                </select> -->
                {{form.city}}
            </div>
        </div>
        <div class="col col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group label-floating">
                <label class="control-label">Write a little description about you</label>
                <!-- <textarea class="form-control" placeholder="">{{user.description}}</textarea> -->
                {{form.description}}
            </div>

            <div class="form-group label-floating is-select">
                <label class="control-label">Your Gender</label>
                <!-- <select name= "gender" class="selectpicker form-control">


                    {% for gender in genders%}

                        <option value="gender.0">{{ gender.1 }}</option>

                    {% endfor%}
               
                </select> -->

                {{form.gender}}

            </div>




        </div>
        <div class="col col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group label-floating">
                <label class="control-label">Your Birthplace</label>
                <!-- <input name = "birthPlace" class="form-control" placeholder="Your birthplace" type="text" value="{{user.birthPlace}}"> -->
                {{form.birthPlace}}
            </div>

            <div class="form-group label-floating">
                <label class="control-label">Your Occupation</label>
                <!-- <input name = "occupation" class="form-control" placeholder="" type="text" value="{{user.occupation}}"> -->
                {{form.occupation}}
            </div>

            <div class="form-group label-floating is-select">
                <label class="control-label">Status</label>
                <!-- <select name = "gender" class="selectpicker form-control">


                    {% for choice in maritialStatus%}

                        <option value="choice.0">{{ choice.1 }}</option>

                    {% endfor%}
                   
                </select> -->
                {{form.maritialStatus}}
            </div>     


        </div>

        <div class="col col-lg-6 col-md-6 col-sm-12 col-12">
            <button type = "submit" class="btn btn-primary btn-lg full-width">Save all Changes</button>
        </div>

    </div>
</form>

{% endblock content %}  


<!-- ... end Personal Information Form  -->

templates/user_profile_page_settings/header.html
{%load static%}
<div class="header-spacer header-spacer-small"></div>

<!-- Main Header Account -->

<div class="main-header">
	<div class="content-bg-wrap bg-account"></div>
	<div class="container">
		<div class="row">
			<div class="col col-lg-8 m-auto col-md-8 col-sm-12 col-12">
				<div class="main-header-content">
					<h1>Your Account Dashboard</h1>
					<p>Welcome to your account dashboard! Here you’ll find everything you need to change your profile
	information, settings, read notifications and requests, view your latest messages, change your pasword and much
	more! Also you can create or manage your own favourite page, have fun!</p>
				</div>
			</div>
		</div>
	</div>
	<img class="img-bottom" src="{% static 'user_profile_page_settings/img/account-bottom.png' %}" alt="friends">
</div>

<!-- ... end Main Header Account -->

templates/user_profile_page_settings/navbar.html
{%load static%}

<!-- Header-BP -->

<header class="header" id="site-header">

	<div class="page-title">
		<a href="{% url 'home_page:home' %}" class="logo">
			<div class="img-wrap">
				<img loading="lazy" src="{% static 'user_profile_page_settings/profileImages/bounlogo.png' %}" width="34" height="34" alt="Olympus">
			</div>
			<div class="title-block" style = "padding-left: 20px;"}>
				<h6 class="logo-title">Boun Learn</h6>
				<div class="sub-title">SOCIAL LEARNING</div>
			</div>
		</a>
	</div>

	<div class="header-content-wrapper">
		<form class="search-bar w-search notification-list friend-requests">
			<div class="form-group with-button">
				<input class="form-control js-user-search" placeholder="Search here people or pages..." type="text">
				<button>
					<svg class="olymp-magnifying-glass-icon"><use xlink:href="{% static 'user_profile_page_settings/svg-icons/sprites/icons.svg' %}#olymp-magnifying-glass-icon"></use></svg>
				</button>
			</div>
		</form>

		<a href="#" class="link-find-friend">Find Friends</a>

		<div class="control-block">

		

			<div class="author-page author vcard inline-items more">
				<div class="author-thumb">
					<img alt="author" src="{{ user.profileImage.url }}" width="50" height="50" class="avatar">
					<span class="icon-status online"></span>
					<div class="more-dropdown more-with-triangle">
						<div class="mCustomScrollbar" data-mcs-theme="dark">
							<div class="ui-block-title ui-block-title-small">
								<h6 class="title">Your Account</h6>
							</div>

							<ul class="account-settings">
								<li>
									<a href="{% url 'user_profile_page_settings:settings' %}">

										<svg class="olymp-menu-icon"><use xlink:href=" {% static 'user_profile_page_settings/svg-icons/sprites/icons.svg' %} #olymp-menu-icon"></use></svg>

										<span>Profile Settings</span>
									</a>
								</li>
								
								<li>
									<a href="{% url 'home_page:logout' %}?next=/login">
										<svg class="olymp-logout-icon"><use xlink:href="{% static 'user_profile_page_settings/svg-icons/sprites/icons.svg' %} #olymp-logout-icon"></use></svg>

										<span>Log Out</span>
									</a>
								</li>
							</ul>



							<div class="ui-block-title ui-block-title-small">
								<h6 class="title">About Olympus</h6>
							</div>

							<ul>
								<li>
									<a href="#">
										<span>Terms and Conditions</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span>FAQs</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span>Careers</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span>Contact</span>
									</a>
								</li>
							</ul>
						</div>

					</div>
				</div>
				<a href="{% url 'user_profile_page_main:profile_page' %}" class="author-name fn">
					<div class="author-title">
						{{user.first_name }} {{user.last_name}} <svg class="olymp-dropdown-arrow-icon"><use xlink:href="{% static 'user_profile_page_settings/svg-icons/sprites/icons.svg' %} #olymp-dropdown-arrow-icon"></use></svg>
					</div>
					<span class="author-subtitle">{{user.occupation}}</span>
				</a>
			</div>

		</div>
	</div>

</header>

<!-- ... end Header-BP -->

templates/user_profile_page_settings/sidebar.html
{%load static%}

<!-- Your Profile  -->
<div class="col col-xl-3 order-xl-1 col-lg-3 order-lg-1 col-md-12 order-md-2 col-sm-12  responsive-display-none">
    <div class="ui-block">

        <div class="your-profile">
            
            <div id="accordion" role="tablist" aria-multiselectable="true">
                <div class="card">
                    <div class="card-header" role="tab" id="headingOne">
                        <h6 class="mb-0">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Profile Settings
                                <svg class="olymp-dropdown-arrow-icon"><use xlink:href="{% static 'user_profile_page_settings/svg-icons/sprites/icons.svg' %} #olymp-dropdown-arrow-icon"></use></svg>
                            </a>
                        </h6>
                    </div>

                    <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                        <ul class="your-profile-menu">
                            <li>
                                <a href="{% url 'user_profile_page_settings:settings' %}">Personal Information</a>
                            </li>
                            <li>
                                <a href="{% url 'user_profile_page_settings:upload_photo' %}">Manage Images</a>
                            </li>
                            <li>
                                <a href="30-YourAccount-ChangePassword.html">Change Password</a>
                            </li>
                            <li>
                                <a href="31-YourAccount-HobbiesAndInterests.html">Hobbies and Interests</a>
                            </li>
                            <li>
                                <a href="32-YourAccount-EducationAndEmployement.html">Education and Employement</a>
                            </li>
                        </ul>
                    </div>
                </div>
          </div>
        </div>
    </div>

</div>

<!-- ... end Your Profile  -->