coLearning_website/urls.py
from django.contrib import admin
from django.urls import path, include
from home_page.views import blog_post
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls')),
    path('profile_settings/',include('user_profile_page_settings.urls')), # profile_settings/<str:pk>/
    path('profile/', include('user_profile_page_main.urls')),
    path('social_space/', include('social_space.urls')),
    path('blog_post/',blog_post)
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home_page/urls.py
from django.urls import path
from home_page.views import home, post_question, post_video, post_blog, SignUp, LoginUser, blog_post, comment_display
from django.contrib.auth import views

app_name = 'home_page'

urlpatterns = [
    
    path('',home, name = 'home'),
    path('post/question/',post_question, name = "post_question"),
    path('post/video/',post_video, name = "post_video"),
    path('post/blog/',post_blog, name='post_blog'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('blog/<int:blog_id>',blog_post, name="blog_post"),
    path('comment/',comment_display, name="comment_display")

]
   

social_space/urls.py
from django.urls import path
from social_space import views

app_name = 'social_space'

urlpatterns = [
    path('<int:space_id>', views.social_space, name='social_space'),
    path('topics/<int:space_id>/<str:type>', views.social_space_topics, name="social_space_topics"),
    path('create-social-space/', views.create_social_space, name="create_social_space"),
    path('join-social-space/', views.join_social_space, name="join_social_space"),
]

user_profile_page_main/urls.py
from django.urls import path
from user_profile_page_main.views import profile_page, post_like, post_dislike, post_reaction, user
from user_profile_page_main import views

app_name = 'user_profile_page_main'

urlpatterns = [
    
    path('',profile_page, name = 'profile_page'),
    path('post-reaction/', post_reaction, name="post_reaction"),
    path('postLike/',post_like, name="post_like"),
    path('postDislike/', post_dislike, name="post_dislike"),
    path('user/<int:user_id>/',user, name='user'),
    path("followToggle/<int:profileUserId>/", views.followToggle, name="followToggle")

]

social_space/models.py
from django.db import models
from user_profile_page_settings.models import User

post_type_choices = (
    ("general", "General"),
    ("community", "Community"),
    ("collaborative", "Collaborative"),
)


# Create your models here.
class SocialSpace(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User, related_name="social_spaces")
    description = models.CharField(max_length=280, blank=True, null=True)
    icon = models.ImageField(null=True, blank=True, upload_to='social_space/icons/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class SocialPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    social_space = models.ForeignKey(SocialSpace, on_delete=models.CASCADE)

    content = models.CharField(max_length=280)
    post_type = models.CharField(max_length=100, choices=post_type_choices, default="general")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.content

social_space/forms.py
from django import forms
from .models import *


class SocialSpaceForm(forms.ModelForm):
    users = forms.CharField(max_length=100)

    class Meta:
        model = SocialSpace
        fields = ['name', 'icon']

    def save(self, commit=True, *args, **kwargs):
        instance = super().save(commit=False)
        print(args)
        print(kwargs)
        owner = User.objects.get(id=kwargs.get("id"))

        def save_m_to_m():
            user_str = self.cleaned_data.get('users')
            instance.users.add(owner)
            for userid in user_str.split(','):
                user = User.objects.get(id=userid)
                instance.users.add(user)

        instance.save()
        save_m_to_m()

        return instance


class SocialPostForm(forms.ModelForm):
    class Meta:
        model = SocialPost
        fields = '__all__'

social_space/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.http.response import JsonResponse
from home_page.models import Post
from user_profile_page_settings.models import User
from .models import SocialSpace, SocialPost
from .forms import SocialSpaceForm, SocialPostForm


def social_space(request, space_id):
    # user = User.objects.get(id=1)
    user_social_space = SocialSpace.objects.get(id=space_id, users__id=request.user.id)
    users_posts = Post.objects.filter(author__in=user_social_space.users.all())
    # print("-------->", users_posts)
    context = {
        'user': request.user,
        'social_space': user_social_space,
        'users_posts': users_posts
    }
    return render(request, 'social_space/social_space_main.html', context)


def social_space_topics(request, space_id, type):
    # user = User.objects.get(id=1)
    social_space_posts = SocialPost.objects.filter(social_space=space_id, post_type=type)
    post_form = SocialPostForm(request.POST or None)

    if request.method == 'POST':

        if post_form.is_valid():
            post_form.save()
            return redirect('social_space:social_space_topics', space_id=space_id, type=type)
        else:
            context = {
                'post_form': post_form,
                'user': request.user,
                'social_space_posts': social_space_posts,
                'social_space_id': space_id,
                'topic_type': type
            }
            return render(request, 'social_space/social_space_topics.html', context)
    else:
        context = {
            'post_form': post_form,
            'user': request.user,
            'social_space_posts': social_space_posts,
            'social_space_id': space_id,
            'topic_type': type
        }
        return render(request, 'social_space/social_space_topics.html', context)


def create_social_space(request):
    form = SocialSpaceForm(request.POST, request.FILES)
    if not request.method == 'POST':
        return JsonResponse({"status": "error"})
    if form.is_valid():
        space_id = form.save(id=request.user.id)
        context = {
            "status": "success",
            "space_id": space_id.id
        }
        return JsonResponse(context)
    else:
        return JsonResponse({"status": "error"})


def join_social_space(request):
    if not request.method == 'POST':
        return JsonResponse({"status": "error"})
    try:
        # user = User.objects.get(id=1)
        social_spaces = request.POST.get('social_spaces')
        for spaceId in social_spaces.split(','):
            instance = SocialSpace.objects.get(id=spaceId)
            instance.users.add(request.user)
        return JsonResponse({"status": "success"})
    except Exception as e:
        print(e)
        return JsonResponse({"status": "error",
                             "message": str(e)
                             })

templates/social_space/social_space_main_header.html
{%load static%}

<!-- Main Header Groups -->

<div class="main-header">
	<div class="content-bg-wrap bg-group"></div>
	<div class="container">
		<div class="row">
			<div class="col col-lg-8 m-auto col-md-8 col-sm-12 col-12">
				<div class="main-header-content">
					<h1>Welcome to the Forums!</h1>
					<p>Here in your learning space you’ll be able to easily create and manage categories and topics to share with the
	 community! We included some of the most used topics, like general, community and collaborative learning each one with a cool
	  and engaging learning topics so you can have fun with them! </p>
				</div>
			</div>
		</div>
	</div>
	
	<img class="img-bottom" src="{% static 'user_profile_page_settings/img/group-bottom.webp' %}" alt="friends">
</div>

<!-- ... end Main Header Groups -->

templates/social_space/social_space_topics.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>

	<title>coLearn</title>

	<!-- Required meta tags always come first -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<!-- Main Font -->
	<script src="{%static 'user_profile_page_settings/js/webfontloader.min.js' %}"></script>
	<script>
		WebFont.load({
			google: {
				families: ['Roboto:300,400,500,700:latin']
			}
		});
	</script>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/Bootstrap/dist/css/bootstrap-reboot.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/Bootstrap/dist/css/bootstrap.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/Bootstrap/dist/css/bootstrap-grid.css' %}">
	
		<!-- Main Styles CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/css/main.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'user_profile_page_settings/css/fonts.min.css' %}">
	

</head>
<body>

	
{%  include 'user_profile_page_settings/navbar.html' %}




<!-- ... end Responsive Header-BP -->
<div class="header-spacer header-spacer-small"></div>



{%  include 'social_space/social_space_main_header.html' %}


<div class="container">
	<div class="row">
		<div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
			<div class="ui-block responsive-flex">
				<div class="ui-block-title">
					<div class="h6 title">
                        <img src="{% static 'user_profile_page_settings/img/tag.png' %}" alt="forum" width="34" height="34">
                        {{topic_type }}</div>
					<form class="w-search">
						<div class="form-group with-button">
							<input class="form-control" type="text" placeholder="Search the forums...">
							<button>
								<svg class="olymp-magnifying-glass-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-magnifying-glass-icon"></use></svg>
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container">

    <!-- News Feed block  -->

    <div class="ui-block">
				
        <!-- News Feed Form  -->
        
        <div class="news-feed-form">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active inline-items" data-toggle="tab" href="#home-1" role="tab" aria-expanded="true">
        
                        <svg class="olymp-status-icon"><use xlink:href="#olymp-status-icon"></use></svg>
        
                        <span>Co Learning Post</span>
                    </a>
                </li>
            </ul>
        
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active" id="home-1" role="tabpanel" aria-expanded="true">
                    <form id = "question-form" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
                        <div class="author-thumb">
                            <img src="{{user.profileImage.url}}" width="40" height="40" alignment="center" alt="author">
                        </div>
                        <div class="form-group with-icon label-floating is-empty">
                            <label class="control-label">Share your question with the community!!</label>
                            <textarea id="id_content" name="content" class="form-control" placeholder=""></textarea>
                        <span class="material-input"></span></div>
                        <div class="errorfield">{{ post_form.errors.content }}</div>
                        <div class="add-options-message">

							<input id = "id_type" type="hidden" name="post_type" value="{{topic_type}}" />
							<input id = "id_author" type="hidden" name="author" value="{{user.id}}" />
							<input id = "social_space" type="hidden" name="social_space" value="{{social_space_id}}" />

                        	<button type="submit" class="btn btn-primary btn-md-2">Post Question</button>
                        	<button class="btn btn-md-2 btn-border-think btn-transparent c-grey">Preview</button>
        
                        </div>
        
                    </form>
                </div>


            </div>
        </div>
        
        <!-- ... end News Feed Form  -->	
            </div>
</div>

<div class="container">
	<div class="row">
		<div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

			<div class="ui-block responsive-flex">

				
				<!-- Open Topic Table -->
				
				<table class="open-topic-table">
				
					<thead>
				
					<tr>
						<th class="author">
							Author
						</th>
				
						<th class="posts">
							Post
						</th>
					</tr>
				
					</thead>
				
					<tbody>
				

				    {% for post in social_space_posts %}
					<tr>
						<td class="topic-date" colspan="2">
							March 24th, 2016 at 6:42 pm
							<a href="#" class="reply-topic">Reply</a>
						</td>
					</tr>
                        <tr>
                            <td class="author-left" >
                                <div class="author-thumb" >
                                    <img src="{{post.author.profileImage.url}}" alt="author">
                                </div>
                                <div class="author-content">
                                    <a href="{% url 'user_profile_page_main:profile_page' %}" class="h6 author-name">{{ post.author.first_name }} {{ post.author.last_name }}</a>
                                    <div class="country">{{ post.author.occupation }}</div>
                                </div>
                            </td>
                            <td class="posts">
                                <p>{{ post.content }}</p>
                            </td>
                        </tr>
                    {% endfor %}
					</tbody>
				</table>
				
				<!-- ... end Open Topic Table -->
			</div>

			
			<!-- Pagination -->
			
			<nav aria-label="Page navigation">
				<ul class="pagination justify-content-center">
					<li class="page-item disabled">
						<a class="page-link" href="#" tabindex="-1">Previous</a>
					</li>
					<li class="page-item"><a class="page-link" href="#">1<div class="ripple-container"><div class="ripple ripple-on ripple-out" style="left: -10.3833px; top: -16.8333px; background-color: rgb(255, 255, 255); transform: scale(16.7857);"></div></div></a></li>
					<li class="page-item"><a class="page-link" href="#">2</a></li>
					<li class="page-item"><a class="page-link" href="#">3</a></li>
					<li class="page-item"><a class="page-link" href="#">...</a></li>
					<li class="page-item"><a class="page-link" href="#">12</a></li>
					<li class="page-item">
						<a class="page-link" href="#">Next</a>
					</li>
				</ul>
			</nav>
			
			<!-- ... end Pagination -->

		</div>

	</div>
</div>




<a class="back-to-top" href="#">
	<img src="{% static 'user_profile_page_settings/svg-icons/back-to-top.svg' %}" alt="arrow" class="back-icon">
</a>







<!-- JS Scripts -->
<script src="{% static 'user_profile_page_settings/js/jquery-3.2.1.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.appear.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.mousewheel.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/perfect-scrollbar.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.matchHeight.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/svgxuse.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/imagesloaded.pkgd.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/Headroom.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/velocity.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/ScrollMagic.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.waypoints.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.countTo.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/popper.min.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/material.min.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/bootstrap-select.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/smooth-scroll.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/selectize.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/swiper.jquery.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/moment.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/daterangepicker.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/simplecalendar.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/fullcalendar.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/isotope.pkgd.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/ajax-pagination.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/Chart.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/chartjs-plugin-deferred.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/circle-progress.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/loader.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/run-chart.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/jquery.gifplayer.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/mediaelement-and-player.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/mediaelement-playlist-plugin.min.js' %}"></script>
<script src="{% static 'user_profile_page_settings/js/sticky-sidebar.js' %}"></script>

<script src="{% static 'user_profile_page_settings/js/base-init.js' %}"></script>
<script defer src="{% static 'user_profile_page_settings/fonts/fontawesome-all.js' %}"></script>

<script src="{% static 'user_profile_page_settings/Bootstrap/dist/js/bootstrap.bundle.js' %}"></script>

</body>
</html>